### ISSUE TITLE
Error laravel 5.6 

### ISSUE THREAD

**Issue by ajiehatajie** [novay/laravel-word-template#1]
`Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In ProviderRepository.php line 208:

  Class 'Novay\WordTemplate\WordServiceProvider' not found

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1`

error nih gan di laravel 5.6 fresh install

**Comment by novay** [comment]
Makasih mas, ada typo di penamaan class ternyata.
Di versi 1.1 untuk versi 5.6 akhirnya **tested** and **fix** 👍
