### ISSUE TITLE
How to use foreach php in rtf ?

### ISSUE THREAD

**Issue by ahmad12azhar** [novay/laravel-word-template#3]
How to use foreach php in rtf, because i want to get in database and the use the data ?

**Comment by maximAbdalov** [comment]
+1

**Comment by novay** [comment]
Sayangnya di package ini cuma bisa sesederhana merubah text mas, belum bisa kustom langsung ke file .rtfnya.
Saran saya sih pakai ini [https://github.com/PHPOffice/PHPWord](https://github.com/PHPOffice/PHPWord)
