### ISSUE TITLE
Mendownload hasil export

### ISSUE THREAD

**Issue by mftlhn** [novay/laravel-word-template#5]
terimakasih packagenya. bagaimana cara untuk mendownload hasil exportnya? saya coba menggunakan Storage::disk('public')->put() tidak bisa

**Comment by novay** [comment]
Seharusnya sih langsung otomatis terdownload begitu di return mas. Tapi, kalau maksudnya mau di simpan ke dalam storage seharusnya bisa cukup begini : 

```
$dokumen = WordTemplate::export($file, $array, $nama_file);
\Storage::disk('local')->put('public/'.$nama_file, $dokumen);
```
