### ISSUE TITLE
How to create RTF file without bloat?

### ISSUE THREAD

**Issue by CharlieNH** [novay/laravel-word-template#8]
Can you tell me what software you used to create your sample RTF file?

When I create an RTF file from Google Docs, it inserts RTF tags around each special character and around each word. It is impossible to find [name_mail] in the document because there are RTF tags around the [, _, and ] characters.

I need to create a simple RTF file with minimum of unnecessary RTF tags. What software do you use?

Thank you!

**Comment by novay** [comment]
I just directly create it manually using VSCode followed by its format type.

**Comment by CharlieNH** [comment]
Thank you. That explains a lot.

When I download a Google Doc in RTF format, it is filled with many, many
unnecessary RTF codes. See attached.

The worst part is that the unnecessary RTF codes break up a token like
[name_mail] into 5 separate pieces separated by long, unnecessary RTF
codes. So str_replace() is impractical.

I need to do mail merge with Google Docs, and I also need to implement
conditional text blocks with the conditional text marked by tokens in the
template instead of being provided from the controller using str_replace().
So I'm writing a bunch of code to handle all that.

If you're interested, I'd be happy to send it to you when it's done. I'm
not smart enough to do all the facade and service provider stuff you did in
Laravel-Word-Template. But once you see the code, if you wanted to work
together to create Laravel-Google-RTF-Template, I think that would be great.

I'll send something for you to look at sometime in the next couple of
weeks. I'll be interested to hear what you think. Thanks!

Charlie

**Comment by novay** [comment]
You're welcome, Charlie!
I think i agree with you, RTF from Google Doc has their own standard, therefore maybe we can fully customize it using their API but its must be limited because there is a pricing term.
About your idea i think its interesting too, it seems there is nothing wrong if we can collaborate with each other while learning from each other too.

**Comment by CharlieNH** [comment]
I agree that the Google API is *not *the way to go. I've tried to work with
it in the past, and it was a terrible experience. I'm not going through
that again!

Thanks for your encouragement! I'm making good progress, so I do hope to
have something for you to look at in the next week or two.

Charlie
